services:
  - type: web
    name: cafetron-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGIN_PATTERNS
        sync: false
      - key: DDL_AUTO
        value: update
      - key: SHOW_SQL
        value: "false"
